/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import groupproject.DBOperations;
import java.awt.Button;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Yasara JLP
 */
public class Admin_Main extends javax.swing.JFrame {

    int xMouse, yMouse;

    public Admin_Main(int userId) {
        initComponents();
        showDate();
        showTime();
        lblUserId.setText(Integer.toString(userId));
        
        // for set table header background
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(240, 240, 240)); // change background colour
        headerRenderer.setHorizontalAlignment(JLabel.CENTER); // change alignment of column captions
        

        for (int i = 0; i < tblRegisteredApplications.getModel().getColumnCount(); i++) {
            tblRegisteredApplications.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);

        }
        tblRegisteredApplications.getTableHeader().setBorder(new BevelBorder(0, Color.WHITE, Color.lightGray));

        // to set column allignments to center
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER); // change alignment of column values
        tblRegisteredApplications.setDefaultRenderer(String.class, centerRenderer);
        
        tblRegisteredApplications.setShowGrid(true);//to show gri in table
        tblRegisteredApplications.setShowHorizontalLines(false);//hide horizontal lines from grid
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegisteredApplications = new javax.swing.JTable();
        btnViewForm = new java.awt.Button();
        btnEditForm = new java.awt.Button();
        btnApproveForm = new java.awt.Button();
        btnRejectForm = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnApplicationRem = new javax.swing.JLabel();
        btnApplicationReg = new javax.swing.JLabel();
        btnApplicantReg = new javax.swing.JLabel();
        btnApplicantRem = new javax.swing.JLabel();
        btnEmpReg = new javax.swing.JLabel();
        btnEmpRem = new javax.swing.JLabel();
        btnSearch = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        btnSend = new javax.swing.JLabel();
        btnResetPass = new javax.swing.JLabel();
        btnReport = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblLogOut = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblUserId = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        panMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panMainMouseDragged(evt);
            }
        });
        panMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panMainMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panMainMouseReleased(evt);
            }
        });
        panMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(9, 18, 72));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CounterClerk/Images/home_Plus_20px.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CounterClerk/Images/home_Password_Reset_20px.png"))); // NOI18N

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CounterClerk/Images/home_Upload_20px.png"))); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CounterClerk/Images/home_Download_20px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        panMain.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 500));

        jPanel2.setBackground(new java.awt.Color(49, 58, 115));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(106, 116, 145));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(224, 227, 221));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registered Applications");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 220, 20));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 20));

        jScrollPane1.setBorder(null);

        tblRegisteredApplications.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRegisteredApplications.setGridColor(new java.awt.Color(204, 204, 204));
        tblRegisteredApplications.setSelectionBackground(new java.awt.Color(79, 142, 255));
        jScrollPane1.setViewportView(tblRegisteredApplications);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 670, 188));

        btnViewForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnViewForm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnViewForm.setLabel("View");
        btnViewForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewFormMouseExited(evt);
            }
        });
        btnViewForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewFormActionPerformed(evt);
            }
        });
        jPanel2.add(btnViewForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 100, -1));

        btnEditForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditForm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnEditForm.setLabel("Edit");
        btnEditForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditFormMouseExited(evt);
            }
        });
        btnEditForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditFormActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 100, -1));

        btnApproveForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnApproveForm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnApproveForm.setLabel("Approve");
        btnApproveForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApproveFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApproveFormMouseExited(evt);
            }
        });
        btnApproveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveFormActionPerformed(evt);
            }
        });
        jPanel2.add(btnApproveForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 100, -1));

        btnRejectForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRejectForm.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnRejectForm.setLabel("Reject");
        btnRejectForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRejectFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRejectFormMouseExited(evt);
            }
        });
        btnRejectForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectFormActionPerformed(evt);
            }
        });
        jPanel2.add(btnRejectForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 100, -1));

        panMain.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 800, 240));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Admin");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CounterClerk/Images/home2.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 130, 140));

        lblTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTime.setText("time");
        jPanel3.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDate.setText("date");
        jPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 94, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 10));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 10, 150));

        btnApplicationRem.setBackground(new java.awt.Color(190, 190, 190));
        btnApplicationRem.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnApplicationRem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnApplicationRem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_rem_user.png"))); // NOI18N
        btnApplicationRem.setText("  Applicant Remove   ");
        btnApplicationRem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnApplicationRem.setOpaque(true);
        btnApplicationRem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApplicationRemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApplicationRemMouseExited(evt);
            }
        });
        jPanel3.add(btnApplicationRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 190, 25));

        btnApplicationReg.setBackground(new java.awt.Color(190, 190, 190));
        btnApplicationReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnApplicationReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnApplicationReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_Add_User.png"))); // NOI18N
        btnApplicationReg.setText(" Applicant Registration   ");
        btnApplicationReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnApplicationReg.setOpaque(true);
        btnApplicationReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApplicationRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApplicationRegMouseExited(evt);
            }
        });
        jPanel3.add(btnApplicationReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 25));

        btnApplicantReg.setBackground(new java.awt.Color(190, 190, 190));
        btnApplicantReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnApplicantReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnApplicantReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_app_reg.png"))); // NOI18N
        btnApplicantReg.setText("  Application Registration");
        btnApplicantReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnApplicantReg.setOpaque(true);
        btnApplicantReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnApplicantRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApplicantRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApplicantRegMouseExited(evt);
            }
        });
        jPanel3.add(btnApplicantReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 190, 25));

        btnApplicantRem.setBackground(new java.awt.Color(190, 190, 190));
        btnApplicantRem.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnApplicantRem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnApplicantRem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_app_rem.png"))); // NOI18N
        btnApplicantRem.setText("  Application Remove");
        btnApplicantRem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnApplicantRem.setOpaque(true);
        btnApplicantRem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApplicantRemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApplicantRemMouseExited(evt);
            }
        });
        jPanel3.add(btnApplicantRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 190, 25));

        btnEmpReg.setBackground(new java.awt.Color(190, 190, 190));
        btnEmpReg.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnEmpReg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEmpReg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_Add_Emp.png"))); // NOI18N
        btnEmpReg.setText("  Employee Registration    ");
        btnEmpReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnEmpReg.setOpaque(true);
        btnEmpReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpRegMouseExited(evt);
            }
        });
        jPanel3.add(btnEmpReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 190, 25));

        btnEmpRem.setBackground(new java.awt.Color(190, 190, 190));
        btnEmpRem.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnEmpRem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEmpRem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_rem_emp.png"))); // NOI18N
        btnEmpRem.setText("  Employee Remove    ");
        btnEmpRem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnEmpRem.setOpaque(true);
        btnEmpRem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpRemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpRemMouseExited(evt);
            }
        });
        jPanel3.add(btnEmpRem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 190, 25));

        btnSearch.setBackground(new java.awt.Color(190, 190, 190));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_Search.png"))); // NOI18N
        btnSearch.setText(" Search Details                 ");
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnSearch.setOpaque(true);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 190, 25));

        btnEdit.setBackground(new java.awt.Color(190, 190, 190));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_Edit.png"))); // NOI18N
        btnEdit.setText("  Edit Details               ");
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnEdit.setOpaque(true);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });
        jPanel3.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 190, 25));

        btnSend.setBackground(new java.awt.Color(190, 190, 190));
        btnSend.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnSend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_Message.png"))); // NOI18N
        btnSend.setText("  Send Messages");
        btnSend.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnSend.setOpaque(true);
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSendMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSendMouseExited(evt);
            }
        });
        jPanel3.add(btnSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 190, 25));

        btnResetPass.setBackground(new java.awt.Color(190, 190, 190));
        btnResetPass.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnResetPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnResetPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_Forgot_Password.png"))); // NOI18N
        btnResetPass.setText("Reset Passwords             ");
        btnResetPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnResetPass.setOpaque(true);
        btnResetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetPassMouseExited(evt);
            }
        });
        jPanel3.add(btnResetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 190, 25));

        btnReport.setBackground(new java.awt.Color(190, 190, 190));
        btnReport.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Admin/Images/home_Report.png"))); // NOI18N
        btnReport.setText(" Report Generation  ");
        btnReport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 170, 170)));
        btnReport.setOpaque(true);
        btnReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReportMouseExited(evt);
            }
        });
        jPanel3.add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 190, 25));

        panMain.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 800, 230));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CounterClerk/Images/home_Logout_20px.png"))); // NOI18N
        lblLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutMouseExited(evt);
            }
        });
        jPanel4.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 5, 20, 20));

        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CounterClerk/Images/home_Horizontal_Line_15px.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        jPanel4.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 5, 20, 20));

        lblUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserId.setText("User");
        jPanel4.add(lblUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 10));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CounterClerk/Images/home_User_20px.png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 30, 30));

        panMain.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 800, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showDate() {
        Date date = new Date();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        lblDate.setText(df.format(date));
    }

    private void showTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                SimpleDateFormat df = new SimpleDateFormat("hh:mm:ss a"); // use HH for het time in 24 hour format
                lblTime.setText(df.format(date));
            }
        }).start();
    }

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
        new DBOperations().setLogStatus(Integer.parseInt(lblUserId.getText()), 0);
        this.dispose();
        new Login.Login().setVisible(true);
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void panMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMainMousePressed
        setOpacity((float) 0.8);
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panMainMousePressed

    private void panMainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMainMouseDragged
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panMainMouseDragged

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseEntered
        lblLogOut.setIcon(new ImageIcon(getClass().getResource("Images/home_Logout_20px_1.png")));
    }//GEN-LAST:event_lblLogOutMouseEntered

    private void lblLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseExited
        lblLogOut.setIcon(new ImageIcon(getClass().getResource("Images/home_Logout_20px.png")));
    }//GEN-LAST:event_lblLogOutMouseExited

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setIcon(new ImageIcon(getClass().getResource("Images/home_Horizontal_Line_15px_1.png")));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new ImageIcon(getClass().getResource("Images/home_Horizontal_Line_15px.png")));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void panMainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMainMouseReleased
        setOpacity((float) 1);
    }//GEN-LAST:event_panMainMouseReleased

    private void btnApplicationRemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicationRemMouseEntered
        setBtnColour(btnApplicationRem);
    }//GEN-LAST:event_btnApplicationRemMouseEntered

    private void btnApplicationRemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicationRemMouseExited
        resetBtnColour(btnApplicationRem);
    }//GEN-LAST:event_btnApplicationRemMouseExited

    private void btnApplicationRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicationRegMouseEntered
        setBtnColour(btnApplicationReg);
    }//GEN-LAST:event_btnApplicationRegMouseEntered

    private void btnApplicationRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicationRegMouseExited
        resetBtnColour(btnApplicationReg);
    }//GEN-LAST:event_btnApplicationRegMouseExited

    private void btnApplicantRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicantRegMouseEntered
        setBtnColour(btnApplicantReg);
    }//GEN-LAST:event_btnApplicantRegMouseEntered

    private void btnApplicantRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicantRegMouseExited
        resetBtnColour(btnApplicantReg);
    }//GEN-LAST:event_btnApplicantRegMouseExited

    private void btnApplicantRemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicantRemMouseEntered
        setBtnColour(btnApplicantRem);
    }//GEN-LAST:event_btnApplicantRemMouseEntered

    private void btnApplicantRemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicantRemMouseExited
        resetBtnColour(btnApplicantRem);
    }//GEN-LAST:event_btnApplicantRemMouseExited

    private void btnEmpRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpRegMouseEntered
        setBtnColour(btnEmpReg);
    }//GEN-LAST:event_btnEmpRegMouseEntered

    private void btnEmpRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpRegMouseExited
        resetBtnColour(btnEmpReg);
    }//GEN-LAST:event_btnEmpRegMouseExited

    private void btnEmpRemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpRemMouseEntered
        setBtnColour(btnEmpRem);
    }//GEN-LAST:event_btnEmpRemMouseEntered

    private void btnEmpRemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpRemMouseExited
        resetBtnColour(btnEmpRem);
    }//GEN-LAST:event_btnEmpRemMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        setBtnColour(btnSearch);
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        resetBtnColour(btnSearch);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        setBtnColour(btnEdit);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        resetBtnColour(btnEdit);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnSendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseEntered
        setBtnColour(btnSend);
    }//GEN-LAST:event_btnSendMouseEntered

    private void btnSendMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseExited
        resetBtnColour(btnSend);
    }//GEN-LAST:event_btnSendMouseExited

    private void btnResetPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPassMouseEntered
        setBtnColour(btnResetPass);
    }//GEN-LAST:event_btnResetPassMouseEntered

    private void btnResetPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPassMouseExited
        resetBtnColour(btnResetPass);
    }//GEN-LAST:event_btnResetPassMouseExited

    private void btnReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseEntered
        setBtnColour(btnReport);
    }//GEN-LAST:event_btnReportMouseEntered

    private void btnReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportMouseExited
        resetBtnColour(btnReport);
    }//GEN-LAST:event_btnReportMouseExited

    private void btnViewFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewFormActionPerformed

    }//GEN-LAST:event_btnViewFormActionPerformed

    private void btnViewFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewFormMouseExited
        resetButtonColour(btnViewForm);
    }//GEN-LAST:event_btnViewFormMouseExited

    private void btnViewFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewFormMouseEntered
        setButtonColour(btnViewForm);
    }//GEN-LAST:event_btnViewFormMouseEntered

    private void btnEditFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditFormMouseEntered
        setButtonColour(btnEditForm);
    }//GEN-LAST:event_btnEditFormMouseEntered

    private void btnEditFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditFormMouseExited
        resetButtonColour(btnEditForm);
    }//GEN-LAST:event_btnEditFormMouseExited

    private void btnEditFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditFormActionPerformed
        
    }//GEN-LAST:event_btnEditFormActionPerformed

    private void btnApproveFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApproveFormMouseEntered
        setButtonColour(btnApproveForm);
    }//GEN-LAST:event_btnApproveFormMouseEntered

    private void btnApproveFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApproveFormMouseExited
        resetButtonColour(btnApproveForm);
    }//GEN-LAST:event_btnApproveFormMouseExited

    private void btnApproveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApproveFormActionPerformed

    private void btnRejectFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectFormMouseEntered
        setButtonColour(btnRejectForm);
    }//GEN-LAST:event_btnRejectFormMouseEntered

    private void btnRejectFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRejectFormMouseExited
        resetButtonColour(btnRejectForm);
    }//GEN-LAST:event_btnRejectFormMouseExited

    private void btnRejectFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRejectFormActionPerformed

    private void btnApplicantRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplicantRegMouseClicked
        new CounterClerk.Register_Application().setVisible(true);
    }//GEN-LAST:event_btnApplicantRegMouseClicked

    private void setBtnColour(JLabel label){
        label.setBackground(new Color(150, 150, 150));
    }
    
    private void resetBtnColour(JLabel label){
        label.setBackground(new Color(190, 190, 190));
    }
    
    private void setButtonColour(Button button){
        button.setBackground(new Color(0,153,0));
        button.setForeground(new Color(255, 255, 255));
    
    }
    
    private void resetButtonColour(Button button){
        button.setBackground(new Color(240,240,240));
        button.setForeground(new Color(0, 0, 0));
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(
                            UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new Admin_Main(0).setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnApplicantReg;
    private javax.swing.JLabel btnApplicantRem;
    private javax.swing.JLabel btnApplicationReg;
    private javax.swing.JLabel btnApplicationRem;
    private java.awt.Button btnApproveForm;
    private javax.swing.JLabel btnEdit;
    private java.awt.Button btnEditForm;
    private javax.swing.JLabel btnEmpReg;
    private javax.swing.JLabel btnEmpRem;
    private java.awt.Button btnRejectForm;
    private javax.swing.JLabel btnReport;
    private javax.swing.JLabel btnResetPass;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel btnSend;
    private java.awt.Button btnViewForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JPanel panMain;
    private javax.swing.JTable tblRegisteredApplications;
    // End of variables declaration//GEN-END:variables
}
