/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import ManagementAssistant.Status_Details;
import Utility.ImageViewer;
import groupproject.DBOperations;
import java.awt.Button;
import java.awt.Color;
import java.awt.Image;
import java.io.InputStream;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Yasara JLP
 */
public class View_Application extends javax.swing.JFrame {

    InputStream survayorPlan, newBuildingPlan, oldBuildingPlan, oldCoC;
    Image image;
    String applicationID;
    private int xMouse, yMouse;
    JFrame parent;

    public View_Application(JFrame parent, String applicationID) {
        initComponents();
        dataAdder(applicationID);
        this.parent = parent;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpIsThereBuilding = new javax.swing.ButtonGroup();
        btnGrpIsPlanApproved = new javax.swing.ButtonGroup();
        btnGrpIsObtainedCoC = new javax.swing.ButtonGroup();
        btnGrpIsEffectToOthers = new javax.swing.ButtonGroup();
        btnGrpEntranceRoad = new javax.swing.ButtonGroup();
        btnGrpWalls = new javax.swing.ButtonGroup();
        btnGrpRoof = new javax.swing.ButtonGroup();
        btnGrpFloor = new javax.swing.ButtonGroup();
        panMain = new javax.swing.JPanel();
        panHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        panCard = new javax.swing.JPanel();
        pan1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtApplicationID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRatePaymentReceiptNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtSurvPlanNo = new javax.swing.JTextField();
        txtBlockNo = new javax.swing.JTextField();
        txtAreaOfTheLand = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtInitName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        btnNext1 = new java.awt.Button();
        txtStreetName = new javax.swing.JTextField();
        txtWardNo = new javax.swing.JTextField();
        btnState = new java.awt.Button();
        pan2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtUse = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        txtCurBuildingArea = new javax.swing.JTextField();
        btnNext2 = new java.awt.Button();
        btnPrev2 = new java.awt.Button();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        scrAreaAddress = new javax.swing.JScrollPane();
        txtAreaAddress = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        scrAreaEffect = new javax.swing.JScrollPane();
        txtAreaEffects = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        txtIsThereBuilding = new javax.swing.JTextField();
        txtCurBuildingPurpose = new javax.swing.JTextField();
        txtCurBuildingPlan = new javax.swing.JTextField();
        txtCurBuildingCoC = new javax.swing.JTextField();
        pan3 = new javax.swing.JPanel();
        btnNext3 = new java.awt.Button();
        btnPrev3 = new java.awt.Button();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        txtGroundFloor = new javax.swing.JTextField();
        jLabel117 = new javax.swing.JLabel();
        txtFirstFloor = new javax.swing.JTextField();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        txtSecondFloor = new javax.swing.JTextField();
        txtThirdFloor = new javax.swing.JTextField();
        jLabel120 = new javax.swing.JLabel();
        txtUnderGroundFloor = new javax.swing.JTextField();
        jLabel121 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel122 = new javax.swing.JLabel();
        txtRoad = new javax.swing.JTextField();
        jLabel123 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        txtBackBoader = new javax.swing.JTextField();
        jLabel125 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        txtRightBoader = new javax.swing.JTextField();
        jLabel127 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        txtLeftBoader = new javax.swing.JTextField();
        jLabel129 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtBuildingCoveredArea = new javax.swing.JTextField();
        jLabel110 = new javax.swing.JLabel();
        pan4 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        btnCancel = new java.awt.Button();
        jLabel89 = new javax.swing.JLabel();
        txtRoadWidth = new javax.swing.JTextField();
        jLabel130 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        btnSurveyorPlan = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        btnBuildingPlan = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel78 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        btnExistingBuildingPlan = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        btnExistingCoC = new javax.swing.JButton();
        btnPrev4 = new java.awt.Button();
        txtTypeOfTheRoad = new javax.swing.JTextField();
        txtwalls = new javax.swing.JTextField();
        txtRoof = new javax.swing.JTextField();
        txtFloor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        panMain.setBackground(new java.awt.Color(255, 255, 255));
        panMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(49, 58, 115), 2));
        panMain.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panMainMouseDragged(evt);
            }
        });
        panMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panMainMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panMainMouseReleased(evt);
            }
        });
        panMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panHeader.setBackground(new java.awt.Color(49, 58, 115));

        jLabel1.setBackground(new java.awt.Color(49, 58, 115));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Application Details");

        javax.swing.GroupLayout panHeaderLayout = new javax.swing.GroupLayout(panHeader);
        panHeader.setLayout(panHeaderLayout);
        panHeaderLayout.setHorizontalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHeaderLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHeaderLayout.setVerticalGroup(
            panHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        panMain.add(panHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 23, 844, -1));

        lblExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 0, 0));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("X");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        panMain.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(846, 2, 20, 20));

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(54, 33, 89));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("-");
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        panMain.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 2, 20, 20));

        panCard.setLayout(new java.awt.CardLayout());

        pan1.setBackground(new java.awt.Color(255, 255, 255));
        pan1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 58, 115));
        jLabel2.setText("2.Details about the Land Which Proposed Devevelopment");
        pan1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 210, 395, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Application ID");
        pan1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 248, 182, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(":");
        pan1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 250, 14, -1));

        txtApplicationID.setEditable(false);
        pan1.add(txtApplicationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 249, 279, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Rate Payment Receipt No");
        pan1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 280, 182, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(":");
        pan1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 282, 14, -1));

        txtRatePaymentReceiptNo.setEditable(false);
        pan1.add(txtRatePaymentReceiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 281, 279, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Street Name");
        pan1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 312, 182, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(":");
        pan1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 314, 14, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Ward No");
        pan1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 344, 182, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(":");
        pan1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 346, 14, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Surveyor Plan No");
        pan1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 376, 182, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(":");
        pan1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 378, 14, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Block No");
        pan1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 408, 182, 20));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(":");
        pan1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 410, 14, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Area Of The Land");
        pan1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 440, 182, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(":");
        pan1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 442, 14, -1));

        txtSurvPlanNo.setEditable(false);
        pan1.add(txtSurvPlanNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 377, 279, -1));

        txtBlockNo.setEditable(false);
        pan1.add(txtBlockNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 409, 170, -1));

        txtAreaOfTheLand.setEditable(false);
        pan1.add(txtAreaOfTheLand, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 441, 170, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("perch(s)");
        pan1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 440, 56, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 58, 115));
        jLabel3.setText("1.Details about the Owner of the Land");
        pan1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 11, 395, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Initial Name");
        pan1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 49, 182, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText(":");
        pan1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 51, 14, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Last Name");
        pan1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 81, 182, 20));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText(":");
        pan1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 83, 14, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("NIC");
        pan1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 113, 182, 20));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(":");
        pan1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 115, 14, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Contact Number");
        pan1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 145, 182, 20));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText(":");
        pan1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 147, 14, -1));

        txtInitName.setEditable(false);
        pan1.add(txtInitName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 279, -1));

        txtLastName.setEditable(false);
        pan1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 82, 279, -1));

        txtNIC.setEditable(false);
        pan1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 114, 279, -1));

        txtPhone.setEditable(false);
        pan1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 146, 279, -1));

        btnNext1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNext1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnNext1.setLabel("Next");
        btnNext1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNext1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNext1MouseExited(evt);
            }
        });
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });
        pan1.add(btnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 471, 78, -1));

        txtStreetName.setEditable(false);
        pan1.add(txtStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 312, 279, -1));

        txtWardNo.setEditable(false);
        pan1.add(txtWardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 344, 279, -1));

        btnState.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnState.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnState.setLabel("State");
        btnState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStateMouseExited(evt);
            }
        });
        btnState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStateActionPerformed(evt);
            }
        });
        pan1.add(btnState, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 11, 100, -1));

        panCard.add(pan1, "card5");

        pan2.setBackground(new java.awt.Color(255, 255, 255));
        pan2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(49, 58, 115));
        jLabel27.setText("3.Proposed Development Details");
        pan2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 210, 395, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Type Of The New Building");
        pan2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 247, 182, 20));

        txtType.setEditable(false);
        pan2.add(txtType, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 247, 279, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Proposed Use");
        pan2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 278, 182, 20));

        txtUse.setEditable(false);
        pan2.add(txtUse, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 278, 279, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Effects On Neighbour Houses");
        pan2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 309, 182, 20));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel44.setText("Is There A Building Already");
        pan2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 25, 182, 20));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText(":");
        pan2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 25, 14, 20));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel46.setText("If Yes : ");
        pan2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 46, 40, 20));

        jLabel69.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel69.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel69.setText("Purpose of The Current Buliding");
        pan2.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 78, 182, 20));

        jLabel70.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel70.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel70.setText(":");
        pan2.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 78, 14, 20));

        txtCurBuildingArea.setEditable(false);
        pan2.add(txtCurBuildingArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 142, 170, -1));

        btnNext2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNext2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnNext2.setLabel("Next");
        btnNext2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNext2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNext2MouseExited(evt);
            }
        });
        btnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext2ActionPerformed(evt);
            }
        });
        pan2.add(btnNext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 471, 78, -1));

        btnPrev2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrev2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnPrev2.setLabel("Prev");
        btnPrev2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrev2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrev2MouseExited(evt);
            }
        });
        btnPrev2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev2ActionPerformed(evt);
            }
        });
        pan2.add(btnPrev2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 471, 78, -1));

        jLabel102.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel102.setText("Plan Approved");
        pan2.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 109, 182, 20));

        jLabel103.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText(":");
        pan2.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 109, 14, 20));

        jLabel104.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel104.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel104.setText("Area Of The Building");
        pan2.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 142, 182, 20));

        jLabel105.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText(":");
        pan2.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 142, 14, 20));

        jLabel106.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel106.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel106.setText("sq ft");
        pan2.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 142, 30, 20));

        jLabel107.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel107.setText("Obtained CoC");
        pan2.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 173, 182, 20));

        jLabel108.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel108.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel108.setText(":");
        pan2.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 173, 14, 20));

        jLabel109.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel109.setText(":");
        pan2.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 247, 14, 20));

        jLabel111.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel111.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel111.setText(":");
        pan2.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 278, 14, 20));

        jLabel112.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel112.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel112.setText(":");
        pan2.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 309, 14, 20));

        txtAreaAddress.setEditable(false);
        txtAreaAddress.setColumns(20);
        txtAreaAddress.setRows(5);
        scrAreaAddress.setViewportView(txtAreaAddress);

        pan2.add(scrAreaAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 391, 280, 70));
        pan2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 64, 485, 10));

        txtAreaEffects.setEditable(false);
        txtAreaEffects.setColumns(20);
        txtAreaEffects.setRows(5);
        scrAreaEffect.setViewportView(txtAreaEffects);

        pan2.add(scrAreaEffect, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 309, 280, 70));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Address");
        pan2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 390, 182, 20));

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel136.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel136.setText(":");
        pan2.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 390, 14, 20));

        txtIsThereBuilding.setEditable(false);
        pan2.add(txtIsThereBuilding, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 25, 279, -1));

        txtCurBuildingPurpose.setEditable(false);
        pan2.add(txtCurBuildingPurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 78, 279, -1));

        txtCurBuildingPlan.setEditable(false);
        pan2.add(txtCurBuildingPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 109, 170, -1));

        txtCurBuildingCoC.setEditable(false);
        pan2.add(txtCurBuildingCoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 173, 170, -1));

        panCard.add(pan2, "card5");

        pan3.setBackground(new java.awt.Color(255, 255, 255));
        pan3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNext3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNext3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnNext3.setLabel("Next");
        btnNext3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNext3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNext3MouseExited(evt);
            }
        });
        btnNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext3ActionPerformed(evt);
            }
        });
        pan3.add(btnNext3, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 471, 78, -1));

        btnPrev3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrev3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnPrev3.setLabel("Prev");
        btnPrev3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrev3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrev3MouseExited(evt);
            }
        });
        btnPrev3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev3ActionPerformed(evt);
            }
        });
        pan3.add(btnPrev3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 471, 78, -1));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel49.setText(" Distance From :");
        pan3.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 130, 20));

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel51.setText("The Road");
        pan3.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 182, 20));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel47.setText("Area Scales of Floors :");
        pan3.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, 20));
        pan3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 485, 10));

        jLabel71.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel71.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel71.setText("Ground Floor");
        pan3.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 182, 20));

        jLabel72.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText(":");
        pan3.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 14, 20));

        jLabel98.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel98.setText("First Floor");
        pan3.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 182, 20));

        jLabel99.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel99.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel99.setText(":");
        pan3.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 14, 20));

        jLabel100.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel100.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel100.setText("Second Floor");
        pan3.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 182, 20));

        jLabel101.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText(":");
        pan3.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 14, 20));

        jLabel113.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel113.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel113.setText("Third Floor");
        pan3.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 182, 20));

        jLabel114.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel114.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel114.setText(":");
        pan3.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 14, 20));

        jLabel115.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel115.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel115.setText("Under Ground");
        pan3.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 182, 20));

        jLabel116.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel116.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel116.setText(":");
        pan3.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 14, 20));
        pan3.add(txtGroundFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 220, -1));

        jLabel117.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel117.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel117.setText("sq ft");
        pan3.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 30, 20));
        pan3.add(txtFirstFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 220, -1));

        jLabel118.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel118.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel118.setText("sq ft");
        pan3.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 30, 20));

        jLabel119.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel119.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel119.setText("sq ft");
        pan3.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 30, 20));
        pan3.add(txtSecondFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 220, -1));
        pan3.add(txtThirdFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 220, -1));

        jLabel120.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel120.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel120.setText("sq ft");
        pan3.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 30, 20));
        pan3.add(txtUnderGroundFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 220, -1));

        jLabel121.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel121.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel121.setText("sq ft");
        pan3.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 30, 20));

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel64.setText("Area Scales of Floors :");
        pan3.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 130, 20));
        pan3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 485, 10));

        jLabel122.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel122.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel122.setText(":");
        pan3.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 14, 20));
        pan3.add(txtRoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 220, -1));

        jLabel123.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel123.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel123.setText("m");
        pan3.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 30, 20));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel65.setText("The Back Boader Of The Land");
        pan3.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 362, 182, 20));

        jLabel124.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel124.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel124.setText(":");
        pan3.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 362, 14, 20));
        pan3.add(txtBackBoader, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 362, 220, -1));

        jLabel125.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel125.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel125.setText("m");
        pan3.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 362, 30, 20));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel66.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel66.setText("The Right Boader Of The Land");
        pan3.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 394, 182, 20));

        jLabel126.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel126.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel126.setText(":");
        pan3.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 394, 14, 20));
        pan3.add(txtRightBoader, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 394, 220, -1));

        jLabel127.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel127.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel127.setText("m");
        pan3.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 394, 30, 20));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel67.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel67.setText("The Left Boader Of The Land");
        pan3.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 426, 182, 20));

        jLabel128.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel128.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel128.setText(":");
        pan3.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 426, 14, 20));
        pan3.add(txtLeftBoader, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 426, 220, -1));

        jLabel129.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel129.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel129.setText("m");
        pan3.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 426, 30, 20));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("The Area Covered by The Building");
        pan3.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 35, 182, 20));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText(":");
        pan3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 35, 14, -1));
        pan3.add(txtBuildingCoveredArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 35, 170, -1));

        jLabel110.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel110.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel110.setText("sq ft");
        pan3.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 35, 30, 20));

        panCard.add(pan3, "card5");

        pan4.setBackground(new java.awt.Color(255, 255, 255));
        pan4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(49, 58, 115));
        jLabel73.setText("4.Attachments");
        pan4.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 236, 395, -1));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel76.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel76.setText("Surveyor Plan");
        pan4.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 273, 182, 20));

        jLabel90.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel90.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel90.setText("Width Of The Entrance Road");
        pan4.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 25, 182, 20));

        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnCancel.setLabel("Cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        pan4.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 471, 78, -1));

        jLabel89.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel89.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel89.setText(":");
        pan4.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 25, 14, 20));
        pan4.add(txtRoadWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 25, 220, -1));

        jLabel130.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel130.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel130.setText("ft");
        pan4.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 25, 30, 20));

        jLabel91.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel91.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel91.setText(":");
        pan4.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 56, 14, 20));

        jLabel92.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel92.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel92.setText("Type Of The Entrance Road");
        pan4.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 56, 182, 20));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel48.setText("Development Details :");
        pan4.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 100, 130, 20));
        pan4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 120, 485, 10));

        jLabel93.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel93.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel93.setText("Walls");
        pan4.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 130, 182, 20));

        jLabel94.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel94.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel94.setText(":");
        pan4.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 130, 14, 20));

        jLabel95.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel95.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel95.setText("Roof");
        pan4.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 161, 182, 20));

        jLabel96.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel96.setText(":");
        pan4.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 161, 14, 20));

        jLabel97.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel97.setText("Floor");
        pan4.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 192, 182, 20));

        jLabel131.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel131.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel131.setText(":");
        pan4.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 192, 14, 20));

        jLabel132.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel132.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel132.setText(":");
        pan4.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 273, 14, 20));

        btnSurveyorPlan.setText("View");
        btnSurveyorPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurveyorPlanActionPerformed(evt);
            }
        });
        pan4.add(btnSurveyorPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 273, 100, -1));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel77.setText("Building Plan");
        pan4.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 304, 182, 20));

        jLabel133.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel133.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel133.setText(":");
        pan4.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 304, 14, 20));

        btnBuildingPlan.setText("View");
        btnBuildingPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuildingPlanActionPerformed(evt);
            }
        });
        pan4.add(btnBuildingPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 304, 100, -1));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel50.setText("Optional");
        pan4.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 340, 130, 20));
        pan4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 360, 485, 10));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel78.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel78.setText("Building Plan Of Existing Building");
        pan4.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 370, 190, 20));

        jLabel134.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel134.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel134.setText(":");
        pan4.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 370, 14, 20));

        btnExistingBuildingPlan.setText("View");
        btnExistingBuildingPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistingBuildingPlanActionPerformed(evt);
            }
        });
        pan4.add(btnExistingBuildingPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 100, -1));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel79.setText("CoC Report Of Existing Building");
        pan4.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 401, 190, 20));

        jLabel135.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel135.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel135.setText(":");
        pan4.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 401, 14, 20));

        btnExistingCoC.setText("View");
        btnExistingCoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistingCoCActionPerformed(evt);
            }
        });
        pan4.add(btnExistingCoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 401, 100, -1));

        btnPrev4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPrev4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnPrev4.setLabel("Prev");
        btnPrev4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrev4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrev4MouseExited(evt);
            }
        });
        btnPrev4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev4ActionPerformed(evt);
            }
        });
        pan4.add(btnPrev4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 471, 78, -1));
        pan4.add(txtTypeOfTheRoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 56, 220, -1));
        pan4.add(txtwalls, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 220, -1));
        pan4.add(txtRoof, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 161, 220, -1));
        pan4.add(txtFloor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 192, 220, -1));

        panCard.add(pan4, "card5");

        panMain.add(panCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 55, 844, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMain, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        this.dispose();
        parent.setState(0);

    }//GEN-LAST:event_lblExitMouseClicked

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void panMainMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMainMousePressed
        setOpacity((float) 0.8);
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panMainMousePressed

    private void panMainMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMainMouseDragged
        int x = evt.getXOnScreen(), y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panMainMouseDragged

    private void btnNext1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext1MouseEntered
        setButtonColour(btnNext1);
    }//GEN-LAST:event_btnNext1MouseEntered

    private void btnNext1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext1MouseExited
        resetButtonColour(btnNext1);
    }//GEN-LAST:event_btnNext1MouseExited

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        hideAllPanels();
        pan2.show();
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnNext2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext2MouseEntered
        setButtonColour(btnNext2);
    }//GEN-LAST:event_btnNext2MouseEntered

    private void btnNext2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext2MouseExited
        resetButtonColour(btnNext2);
    }//GEN-LAST:event_btnNext2MouseExited

    private void btnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext2ActionPerformed
        hideAllPanels();
        pan3.show();
    }//GEN-LAST:event_btnNext2ActionPerformed

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        setButtonColour(btnCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        resetButtonColour(btnCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
        parent.setState(0);

    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnPrev2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrev2MouseEntered
        setButtonColour(btnPrev2);
    }//GEN-LAST:event_btnPrev2MouseEntered

    private void btnPrev2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrev2MouseExited
        resetButtonColour(btnPrev2);
    }//GEN-LAST:event_btnPrev2MouseExited

    private void btnPrev2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev2ActionPerformed
        hideAllPanels();
        pan1.show();
    }//GEN-LAST:event_btnPrev2ActionPerformed

    private void btnNext3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext3MouseEntered
        setButtonColour(btnNext3);
    }//GEN-LAST:event_btnNext3MouseEntered

    private void btnNext3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNext3MouseExited
        resetButtonColour(btnNext3);
    }//GEN-LAST:event_btnNext3MouseExited

    private void btnNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext3ActionPerformed

        hideAllPanels();
        pan4.show();


    }//GEN-LAST:event_btnNext3ActionPerformed

    private void btnPrev3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrev3MouseEntered
        setButtonColour(btnPrev3);
    }//GEN-LAST:event_btnPrev3MouseEntered

    private void btnPrev3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrev3MouseExited
        resetButtonColour(btnPrev3);
    }//GEN-LAST:event_btnPrev3MouseExited

    private void btnPrev3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev3ActionPerformed
        hideAllPanels();
        pan2.show();
    }//GEN-LAST:event_btnPrev3ActionPerformed

    private void panMainMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panMainMouseReleased
        setOpacity((float) 1);
    }//GEN-LAST:event_panMainMouseReleased

    private void btnPrev4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrev4MouseEntered
        setButtonColour(btnPrev4);
    }//GEN-LAST:event_btnPrev4MouseEntered

    private void btnPrev4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrev4MouseExited
        resetButtonColour(btnPrev4);
    }//GEN-LAST:event_btnPrev4MouseExited

    private void btnPrev4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev4ActionPerformed
        hideAllPanels();
        pan3.show();
    }//GEN-LAST:event_btnPrev4ActionPerformed

    private void btnSurveyorPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurveyorPlanActionPerformed
        try {
            image = ImageIO.read(survayorPlan);
            new ImageViewer(image).setVisible(true);
        } catch (Exception e) {
            System.out.println("exeption in Image View " + e);
        }

    }//GEN-LAST:event_btnSurveyorPlanActionPerformed

    private void btnBuildingPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuildingPlanActionPerformed
        try {
            image = ImageIO.read(newBuildingPlan);
            new ImageViewer(image).setVisible(true);
        } catch (Exception e) {
            System.out.println("exeption in Image View " + e);
        }
    }//GEN-LAST:event_btnBuildingPlanActionPerformed

    private void btnExistingBuildingPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistingBuildingPlanActionPerformed
        try {
            image = ImageIO.read(oldBuildingPlan);
            new ImageViewer(image).setVisible(true);
        } catch (Exception e) {
            System.out.println("exeption in Image View " + e);
        }
    }//GEN-LAST:event_btnExistingBuildingPlanActionPerformed

    private void btnExistingCoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistingCoCActionPerformed
        try {
            image = ImageIO.read(oldCoC);
            new ImageViewer(image).setVisible(true);
        } catch (Exception e) {
            System.out.println("exeption in Image View " + e);
        }
    }//GEN-LAST:event_btnExistingCoCActionPerformed

    private void btnStateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStateMouseEntered
        setButtonColour(btnState);
    }//GEN-LAST:event_btnStateMouseEntered

    private void btnStateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStateMouseExited
        resetButtonColour(btnState);
    }//GEN-LAST:event_btnStateMouseExited

    private void btnStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStateActionPerformed
        new Status_Details(txtApplicationID.getText()).setVisible(true);
    }//GEN-LAST:event_btnStateActionPerformed

    private void hideAllPanels() {
        pan1.hide();
        pan2.hide();
        pan3.hide();
        pan4.hide();

    }

    private void setButtonColour(Button button) {
        button.setBackground(new Color(0, 153, 0));
        button.setForeground(new Color(255, 255, 255));

    }

    private void resetButtonColour(Button button) {
        button.setBackground(new Color(240, 240, 240));
        button.setForeground(new Color(0, 0, 0));

    }

    private void dataAdder(String applicationID) {
        ResultSet application, applicant;
        DBOperations dbops = new DBOperations();
        application = dbops.getApplication(applicationID, 0);
        try {
            application.next();
            String ownerNIC = application.getString("owner_nic");
            applicant = dbops.getApplicant(ownerNIC, 0);
            applicant.next();
            // set owner details
            txtInitName.setText(applicant.getString("init_name"));
            txtLastName.setText(applicant.getString("last_name"));
            txtNIC.setText(ownerNIC);
            txtPhone.setText(applicant.getString("phone"));

            // set application details
            txtApplicationID.setText(application.getString("application_id"));
            txtRatePaymentReceiptNo.setText(application.getString("rate_payment_recipt_no"));
            txtStreetName.setText(application.getString("street_name"));
            txtWardNo.setText(application.getString("ward_no"));
            txtSurvPlanNo.setText(application.getString("survayor_plan_no"));
            txtBlockNo.setText(application.getString("block_no"));
            txtAreaOfTheLand.setText(application.getString("area_of_the_land"));

            if (application.getDouble("area_of_the_current_building") == 0) {
                txtIsThereBuilding.setText("No");
            } else {
                txtIsThereBuilding.setText("Yes");
            }
            txtCurBuildingPurpose.setText(application.getString("purpose_of_current_building"));
            txtCurBuildingPlan.setText(application.getBoolean("is_current_building_plan_approved") ? "Yes" : "No");
            txtCurBuildingArea.setText(Double.toString(application.getDouble("area_of_the_current_building")));
            txtCurBuildingCoC.setText(application.getBoolean("is_current_building_has_coc") ? "Yes" : "No");
            txtType.setText(application.getString("type_of_the_new_building"));
            txtUse.setText(application.getString("proposed_use"));
            txtAreaEffects.setText(application.getString("effect_on_neihbours"));
            txtAreaAddress.setText(application.getString("address"));

            txtBuildingCoveredArea.setText(Double.toString(application.getDouble("area_covered_by_building")));
            txtGroundFloor.setText(Double.toString(application.getDouble("ground_floor_area")));
            txtFirstFloor.setText(Double.toString(application.getDouble("first_floor_area")));
            txtSecondFloor.setText(Double.toString(application.getDouble("second_floor_area")));
            txtThirdFloor.setText(Double.toString(application.getDouble("third_floor_area")));
            txtUnderGroundFloor.setText(Double.toString(application.getDouble("under_ground_area")));
            txtRoad.setText(Double.toString(application.getDouble("distance_from_road")));
            txtBackBoader.setText(Double.toString(application.getDouble("distance_from_back_boader")));
            txtRightBoader.setText(Double.toString(application.getDouble("distance_from_right_boader")));
            txtLeftBoader.setText(Double.toString(application.getDouble("distance_from_left_boader")));

            txtRoadWidth.setText(Float.toString(application.getFloat("width_of_the_entarence_road")));
            txtTypeOfTheRoad.setText(application.getString("type_of_the_road"));
            txtwalls.setText(application.getBoolean("completed_walls") ? "Yes" : "No");
            txtRoof.setText(application.getBoolean("completed_roof") ? "Yes" : "No");
            txtFloor.setText(application.getBoolean("completed_floor") ? "Yes" : "No");
            // images
            survayorPlan = application.getBinaryStream("survayor_plan");
            newBuildingPlan = application.getBinaryStream("new_building_plan");;
            oldBuildingPlan = application.getBinaryStream("exiting_building_plan");;
            oldCoC = application.getBinaryStream("exiting_building_coc");

        } catch (Exception e) {
            System.out.println("exeption in dataAdder method in View_Application " + e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(
                            UIManager.getSystemLookAndFeelClassName());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new View_Application(null, null).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuildingPlan;
    private java.awt.Button btnCancel;
    private javax.swing.JButton btnExistingBuildingPlan;
    private javax.swing.JButton btnExistingCoC;
    private javax.swing.ButtonGroup btnGrpEntranceRoad;
    private javax.swing.ButtonGroup btnGrpFloor;
    private javax.swing.ButtonGroup btnGrpIsEffectToOthers;
    private javax.swing.ButtonGroup btnGrpIsObtainedCoC;
    private javax.swing.ButtonGroup btnGrpIsPlanApproved;
    private javax.swing.ButtonGroup btnGrpIsThereBuilding;
    private javax.swing.ButtonGroup btnGrpRoof;
    private javax.swing.ButtonGroup btnGrpWalls;
    private java.awt.Button btnNext1;
    private java.awt.Button btnNext2;
    private java.awt.Button btnNext3;
    private java.awt.Button btnPrev2;
    private java.awt.Button btnPrev3;
    private java.awt.Button btnPrev4;
    private java.awt.Button btnState;
    private javax.swing.JButton btnSurveyorPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JPanel pan1;
    private javax.swing.JPanel pan2;
    private javax.swing.JPanel pan3;
    private javax.swing.JPanel pan4;
    private javax.swing.JPanel panCard;
    private javax.swing.JPanel panHeader;
    private javax.swing.JPanel panMain;
    private javax.swing.JScrollPane scrAreaAddress;
    private javax.swing.JScrollPane scrAreaEffect;
    private javax.swing.JTextField txtApplicationID;
    private javax.swing.JTextArea txtAreaAddress;
    private javax.swing.JTextArea txtAreaEffects;
    private javax.swing.JTextField txtAreaOfTheLand;
    private javax.swing.JTextField txtBackBoader;
    private javax.swing.JTextField txtBlockNo;
    private javax.swing.JTextField txtBuildingCoveredArea;
    private javax.swing.JTextField txtCurBuildingArea;
    private javax.swing.JTextField txtCurBuildingCoC;
    private javax.swing.JTextField txtCurBuildingPlan;
    private javax.swing.JTextField txtCurBuildingPurpose;
    private javax.swing.JTextField txtFirstFloor;
    private javax.swing.JTextField txtFloor;
    private javax.swing.JTextField txtGroundFloor;
    private javax.swing.JTextField txtInitName;
    private javax.swing.JTextField txtIsThereBuilding;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLeftBoader;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRatePaymentReceiptNo;
    private javax.swing.JTextField txtRightBoader;
    private javax.swing.JTextField txtRoad;
    private javax.swing.JTextField txtRoadWidth;
    private javax.swing.JTextField txtRoof;
    private javax.swing.JTextField txtSecondFloor;
    private javax.swing.JTextField txtStreetName;
    private javax.swing.JTextField txtSurvPlanNo;
    private javax.swing.JTextField txtThirdFloor;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtTypeOfTheRoad;
    private javax.swing.JTextField txtUnderGroundFloor;
    private javax.swing.JTextField txtUse;
    private javax.swing.JTextField txtWardNo;
    private javax.swing.JTextField txtwalls;
    // End of variables declaration//GEN-END:variables

}
